AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Express.js API using @vendia/serverless-express

Globals:
  Function:
    Timeout: 15
    MemorySize: 512

Resources:
  ExpressJsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: index.handler
      Runtime: nodejs20.x

      VpcConfig:
        SubnetIds:
          - subnet-0a11c12998ff540e1  #pvt subnet_id 1
          - subnet-065a73345490e0ee8  #pvt subnet_id 2
        SecurityGroupIds:
          - sg-019f671390240930c       #sg_of lamda fnc( configured rds sg in aws console to allow requests from this lambda fnc)

      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY


