AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Express.js API using @vendia/serverless-express

Globals:
  Function:
    Timeout: 15
    MemorySize: 512

Resources:
  ExpressJsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: index.handler
      Runtime: nodejs20.x

      # ❗ REMOVE VpcConfig COMPLETELY 
      # Lambda is now outside the VPC so it can talk to internet + SQS etc.

      Environment:
        Variables:
          DB_HOST: "logstream-2-db.czegikcsabng.ap-south-1.rds.amazonaws.com"
          DB_PORT: "5432"
          DB_NAME: "Logstream_DB"
          DB_USER: "masterUser"
          DB_PASSWORD: "Admin$1234"

      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
